name: Build Boards

on:
  push:
    branches:
      - main
      - ci/* # for ci test
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  prepare:
    name: Determine variants to build
    runs-on: ubuntu-latest
    container:
      image: espressif/idf:v6.0.2
    outputs:
      variants: ${{ steps.select.outputs.variants }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Test build tooling
        run: python -m unittest discover -s scripts/tests -v

      - id: list
        name: Get all variant list
        run: |
          echo "all_variants=$(python scripts/build.py --list-boards --json)" >> $GITHUB_OUTPUT

      - id: select
        name: Select variants based on changes
        shell: python
        run: |
          import os, json
          
          event_name = "${{ github.event_name }}"
          
          if event_name == "push":
              all_variants = ${{ steps.list.outputs.all_variants }}
              with open(os.environ['GITHUB_OUTPUT'], 'a') as f:
                  f.write(f"variants={json.dumps(all_variants)}\n")

  build:
    name: Build ${{ matrix.full_name }}
    needs: prepare
    if: ${{ needs.prepare.outputs.variants != '[]' }}
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.prepare.outputs.variants) }}
    runs-on: ubuntu-latest
    container:
      image: espressif/idf:v6.0.2
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build current variant
        shell: bash
        run: |
          source $IDF_PATH/export.sh
          python scripts/build.py --board ${{ matrix.board }} --name ${{ matrix.name }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: xiaozhi_s3_${{ matrix.full_name }}_${{ github.sha }}
          path: build/merged-binary.bin
          if-no-files-found: error
